<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserPreference extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'want_age_from',
        'want_age_to',
        'want_gender_man',
        'want_gender_woman',
        'want_gender_ts_woman',
        'want_gender_ts_man',
        'want_gender_cd_woman',
        'want_gender_cd_man',
        'want_gender_couple_mf',
        'want_gender_couple_mm',
        'want_gender_couple_ff',
        'want_gender_group',
        'want_body_tiny',
        'want_body_slim',
        'want_body_average',
        'want_body_muscular',
        'want_body_curvy',
        'want_body_thick',
        'want_body_bbw',
        'want_ethnicity_white',
        'want_ethnicity_asian',
        'want_ethnicity_latino',
        'want_ethnicity_indian',
        'want_ethnicity_black',
        'want_ethnicity_other',
        'want_hair_color_light',
        'want_hair_color_medium',
        'want_hair_color_dark',
        'want_hair_color_red',
        'want_hair_color_gray',
        'want_hair_color_other',
        'want_hair_length_bald',
        'want_hair_length_short',
        'want_hair_length_medium',
        'want_hair_length_long',
        'want_tattoos_none',
        'want_tattoos_some',
        'want_tattoos_all_over',
        'want_looks_ugly',
        'want_looks_plain',
        'want_looks_quirks',
        'want_looks_average',
        'want_looks_attractive',
        'want_looks_hottie',
        'want_looks_supermodel',
        'want_intelligence_slow',
        'want_intelligence_bit_slow',
        'want_intelligence_average',
        'want_intelligence_faster',
        'want_intelligence_genius',
        'want_bedroom_personality_passive',
        'want_bedroom_personality_shy',
        'want_bedroom_personality_confident',
        'want_bedroom_personality_aggressive',
        'want_pubic_hair_shaved',
        'want_pubic_hair_trimmed',
        'want_pubic_hair_average',
        'want_pubic_hair_natural',
        'want_pubic_hair_hairy',
        'want_penis_size_tiny',
        'want_penis_size_skinny',
        'want_penis_size_average',
        'want_penis_size_thick',
        'want_penis_size_huge',
        'want_body_hair_smooth',
        'want_body_hair_average',
        'want_body_hair_hairy',
        'want_breast_size_tiny',
        'want_breast_size_small',
        'want_breast_size_average',
        'want_breast_size_large',
        'want_breast_size_huge',
        'want_safe_sex',
        'want_bareback_sex',
        'want_oral_give',
        'want_oral_receive',
        'want_anal_top',
        'want_anal_bottom',
        'want_filming',
        'want_voyeur',
        'want_exhibitionist',
        'want_roleplay',
        'want_spanking',
        'want_dom',
        'want_sub',
        'want_strapon',
        'want_cuckold',
        'want_furry',
        'where_my_place',
        'where_you_host',
        'where_car_date',
        'where_hotel_i_pay',
        'where_hotel_you_pay',
        'where_hotel_split',
        'where_bar_club',
        'where_gym_sauna',
        'where_nude_beach',
        'where_other',
        'mutual_long_term',
        'mutual_no_strings',
        'mutual_wear_mask',
        'mutual_only_play_safe',
        'mutual_proof_of_testing',
        'no_cigs',
        'no_light_drink',
        'no_heavy_drink',
        'no_marijuana',
        'no_psychedelics',
        'no_drugs',
        'no_herpes',
        'no_warts',
        'no_hepatitis',
        'no_other_stis',
        'no_hiv',
        'no_married_they_know',
        'no_married_secret',
        'no_poly',
        'no_disabled',
    ];

    protected $casts = [
        'want_age_from' => 'integer',
        'want_age_to' => 'integer',
        'want_gender_man' => 'boolean',
        'want_gender_woman' => 'boolean',
        'want_gender_ts_woman' => 'boolean',
        'want_gender_ts_man' => 'boolean',
        'want_gender_cd_woman' => 'boolean',
        'want_gender_cd_man' => 'boolean',
        'want_gender_couple_mf' => 'boolean',
        'want_gender_couple_mm' => 'boolean',
        'want_gender_couple_ff' => 'boolean',
        'want_gender_group' => 'boolean',
        'want_body_tiny' => 'boolean',
        'want_body_slim' => 'boolean',
        'want_body_average' => 'boolean',
        'want_body_muscular' => 'boolean',
        'want_body_curvy' => 'boolean',
        'want_body_thick' => 'boolean',
        'want_body_bbw' => 'boolean',
        'want_ethnicity_white' => 'boolean',
        'want_ethnicity_asian' => 'boolean',
        'want_ethnicity_latino' => 'boolean',
        'want_ethnicity_indian' => 'boolean',
        'want_ethnicity_black' => 'boolean',
        'want_ethnicity_other' => 'boolean',
        'want_hair_color_light' => 'boolean',
        'want_hair_color_medium' => 'boolean',
        'want_hair_color_dark' => 'boolean',
        'want_hair_color_red' => 'boolean',
        'want_hair_color_gray' => 'boolean',
        'want_hair_color_other' => 'boolean',
        'want_hair_length_bald' => 'boolean',
        'want_hair_length_short' => 'boolean',
        'want_hair_length_medium' => 'boolean',
        'want_hair_length_long' => 'boolean',
        'want_tattoos_none' => 'boolean',
        'want_tattoos_some' => 'boolean',
        'want_tattoos_all_over' => 'boolean',
        'want_looks_ugly' => 'boolean',
        'want_looks_plain' => 'boolean',
        'want_looks_quirks' => 'boolean',
        'want_looks_average' => 'boolean',
        'want_looks_attractive' => 'boolean',
        'want_looks_hottie' => 'boolean',
        'want_looks_supermodel' => 'boolean',
        'want_intelligence_slow' => 'boolean',
        'want_intelligence_bit_slow' => 'boolean',
        'want_intelligence_average' => 'boolean',
        'want_intelligence_faster' => 'boolean',
        'want_intelligence_genius' => 'boolean',
        'want_bedroom_personality_passive' => 'boolean',
        'want_bedroom_personality_shy' => 'boolean',
        'want_bedroom_personality_confident' => 'boolean',
        'want_bedroom_personality_aggressive' => 'boolean',
        'want_pubic_hair_shaved' => 'boolean',
        'want_pubic_hair_trimmed' => 'boolean',
        'want_pubic_hair_average' => 'boolean',
        'want_pubic_hair_natural' => 'boolean',
        'want_pubic_hair_hairy' => 'boolean',
        'want_penis_size_tiny' => 'boolean',
        'want_penis_size_skinny' => 'boolean',
        'want_penis_size_average' => 'boolean',
        'want_penis_size_thick' => 'boolean',
        'want_penis_size_huge' => 'boolean',
        'want_body_hair_smooth' => 'boolean',
        'want_body_hair_average' => 'boolean',
        'want_body_hair_hairy' => 'boolean',
        'want_breast_size_tiny' => 'boolean',
        'want_breast_size_small' => 'boolean',
        'want_breast_size_average' => 'boolean',
        'want_breast_size_large' => 'boolean',
        'want_breast_size_huge' => 'boolean',
        'want_safe_sex' => 'boolean',
        'want_bareback_sex' => 'boolean',
        'want_oral_give' => 'boolean',
        'want_oral_receive' => 'boolean',
        'want_anal_top' => 'boolean',
        'want_anal_bottom' => 'boolean',
        'want_filming' => 'boolean',
        'want_voyeur' => 'boolean',
        'want_exhibitionist' => 'boolean',
        'want_roleplay' => 'boolean',
        'want_spanking' => 'boolean',
        'want_dom' => 'boolean',
        'want_sub' => 'boolean',
        'want_strapon' => 'boolean',
        'want_cuckold' => 'boolean',
        'want_furry' => 'boolean',
        'where_my_place' => 'boolean',
        'where_you_host' => 'boolean',
        'where_car_date' => 'boolean',
        'where_hotel_i_pay' => 'boolean',
        'where_hotel_you_pay' => 'boolean',
        'where_hotel_split' => 'boolean',
        'where_bar_club' => 'boolean',
        'where_gym_sauna' => 'boolean',
        'where_nude_beach' => 'boolean',
        'where_other' => 'boolean',
        'mutual_long_term' => 'boolean',
        'mutual_no_strings' => 'boolean',
        'mutual_wear_mask' => 'boolean',
        'mutual_only_play_safe' => 'boolean',
        'mutual_proof_of_testing' => 'boolean',
        'no_cigs' => 'boolean',
        'no_light_drink' => 'boolean',
        'no_heavy_drink' => 'boolean',
        'no_marijuana' => 'boolean',
        'no_psychedelics' => 'boolean',
        'no_drugs' => 'boolean',
        'no_herpes' => 'boolean',
        'no_warts' => 'boolean',
        'no_hepatitis' => 'boolean',
        'no_other_stis' => 'boolean',
        'no_hiv' => 'boolean',
        'no_married_they_know' => 'boolean',
        'no_married_secret' => 'boolean',
        'no_poly' => 'boolean',
        'no_disabled' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(FwberUser::class, 'user_id');
    }
}
