-- Legacy matcher compatibility columns for users table
-- MySQL 8.0+ required for IF NOT EXISTS on ADD COLUMN

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `distance` varchar(16) DEFAULT 'dist50m',
  ADD COLUMN IF NOT EXISTS `profileDone` TINYINT(1) DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `verified` TINYINT(1) DEFAULT 1;

-- Gender preference flags
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantGenderMan` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderWoman` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderTSWoman` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderTSMan` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderCDWoman` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderCDMan` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderCoupleMF` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderCoupleMM` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderCoupleFF` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantGenderGroup` TINYINT(1) DEFAULT 0;

-- Body type preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantBodyTiny` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodySlim` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyMuscular` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyCurvy` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyThick` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyBBW` TINYINT(1) DEFAULT 0;

-- Ethnicity preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityWhite` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityAsian` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityLatino` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityIndian` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityBlack` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantEthnicityOther` TINYINT(1) DEFAULT 0;

-- Hair color preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantHairColorLight` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairColorMedium` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairColorDark` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairColorRed` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairColorGray` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairColorOther` TINYINT(1) DEFAULT 0;

-- Hair length preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantHairLengthBald` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairLengthShort` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairLengthMedium` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantHairLengthLong` TINYINT(1) DEFAULT 0;

-- Tattoo preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantTattoosNone` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantTattoosSome` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantTattoosAllOver` TINYINT(1) DEFAULT 0;

-- Looks preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantLooksUgly` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksPlain` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksQuirky` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksAttractive` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksHottie` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantLooksSuperModel` TINYINT(1) DEFAULT 0;

-- Intelligence preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantIntelligenceGoodHands` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantIntelligenceBitSlow` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantIntelligenceAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantIntelligenceFaster` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantIntelligenceGenius` TINYINT(1) DEFAULT 0;

-- Bedroom personality preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantBedroomPersonalityPassive` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBedroomPersonalityShy` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBedroomPersonalityConfident` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBedroomPersonalityAggressive` TINYINT(1) DEFAULT 0;

-- Pubic hair preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantPubicHairShaved` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPubicHairTrimmed` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPubicHairCropped` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPubicHairNatural` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPubicHairHairy` TINYINT(1) DEFAULT 0;

-- Penis size preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantPenisSizeTiny` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPenisSizeSkinny` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPenisSizeAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPenisSizeThick` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantPenisSizeHuge` TINYINT(1) DEFAULT 0;

-- Body hair preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantBodyHairSmooth` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyHairAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBodyHairHairy` TINYINT(1) DEFAULT 0;

-- Breast size preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantBreastSizeTiny` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBreastSizeSmall` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBreastSizeAverage` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBreastSizeLarge` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBreastSizeHuge` TINYINT(1) DEFAULT 0;

-- Lifestyle & health flags
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_smokeCigarettes` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noCigs` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_lightDrinker` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noLightDrink` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_heavyDrinker` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noHeavyDrink` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_smokeMarijuana` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noMarijuana` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_psychedelics` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noPsychedelics` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_otherDrugs` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noDrugs` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_haveWarts` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noWarts` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_haveHerpes` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noHerpes` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_haveHepatitis` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noHepatitis` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_haveOtherSTI` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noOtherSTIs` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_haveHIV` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noHIV` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_marriedTheyKnow` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noMarriedTheyKnow` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_marriedSecret` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noMarriedSecret` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_poly` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noPoly` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_disability` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_noDisabled` TINYINT(1) DEFAULT 0;

-- Sexual activities
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_wantSafeSex` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantBarebackSex` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantOralGive` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantOralReceive` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantAnalTop` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantAnalBottom` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantFilming` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantVoyeur` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantExhibitionist` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantRoleplay` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantSpanking` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantDom` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantSub` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantStrapon` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantCuckold` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_wantFurry` TINYINT(1) DEFAULT 0;

-- Meeting preferences
ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `b_whereMyPlace` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereYouHost` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereCarDate` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereHotelIPay` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereHotelYouPay` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereHotelSplit` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereBarClub` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereGymSauna` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereNudeBeach` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `b_whereOther` TINYINT(1) DEFAULT 0;
