model = "gpt-5-codex-high"
model_reasoning_effort = "medium"
windows_wsl_setup_acknowledged = true

# Global MCP server timeout settings (keep short to prevent lingering processes)
mcp_server_startup_timeout_ms = 90000
mcp_server_timeout_ms = 30000

# Security: explicit env allowlist and least-privilege filesystem roots
[security]
env_allowlist = [
  "PROJECT_ROOT",
  "AI_COORDINATION_DIR",
  "MCP_CONFIG_PATH",
  "MCP_FILESYSTEM_ROOTS",
  "LOG_DIR",
  "TEMP_DIR",
  "SERENA_HOME",
  "ZEN_HOME",
  "OPENAI_API_KEY",
  "OPENAI_ORG",
  "ANTHROPIC_API_KEY",
  "GEMINI_API_KEY",
  "XAI_API_KEY",
  "OPENROUTER_API_KEY",
  "GITHUB_TOKEN",
  "POSTGRES_URL",
  "USERPROFILE",
  "PATH"
]
filesystem_roots = [
  "C:\\Users\\hyper\\fwber",
  "C:\\Users\\hyper\\fwber\\AI_COORDINATION"
]

# Use globally installed MCP server executables (no npx) to avoid stdio handshake issues

# Filesystem server (global bin: mcp-server-filesystem)
# Note: This server takes the root path as its argument and communicates over stdio by default
[mcp_servers.filesystem]
command = "mcp-server-filesystem"
args = ["C:\\Users\\hyper\\fwber\\"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Sequential Thinking server (global bin: mcp-server-sequential-thinking)
[mcp_servers.sequential-thinking]
command = "mcp-server-sequential-thinking"
args = ["stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Gemini MCP (global bin: gemini-mcp)
[mcp_servers.gemini-mcp]
command = "gemini-mcp"
args = ["stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Codex MCP Server (global bin: codex-mcp-server)
[mcp_servers.codex-mcp-server]
command = "codex-mcp-server"
args = ["stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Serena MCP (Python/uv). Requires uv at %USERPROFILE%\.local\bin\uv.exe and Serena repo at %USERPROFILE%\serena
[mcp_servers.serena]
command = "%USERPROFILE%\\.local\\bin\\uv.exe"
args = ["run","--directory","%USERPROFILE%\\serena\\","serena","start-mcp-server","--context","codex","--project","C:\\Users\\hyper\\fwber\\"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Project trust (required by Codex for workspace operations)
[projects.'\\?\\C:\\Users\\hyper\\fwber']
trust_level = "trusted"