USE fwber_production;
CREATE TABLE federation_follows (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_uri VARCHAR(255) NOT NULL,
  target_uri VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL
);
CREATE TABLE federation_inbox (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  activity_id VARCHAR(255) NOT NULL UNIQUE,
  actor_uri VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  payload JSON NOT NULL,
  processed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL
);
CREATE TABLE federation_outbox (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  activity_id VARCHAR(255) NOT NULL UNIQUE,
  actor_uri VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  payload JSON NOT NULL,
  delivered_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL
);
