model = "gpt-5-codex"
model_reasoning_effort = "medium"
windows_wsl_setup_acknowledged = true

# Global MCP server timeout settings
mcp_server_startup_timeout_ms = 300000
mcp_server_timeout_ms = 600000

# Test with just one server
[mcp_servers.memory]
command = "cmd"
args = ["/c","npx.cmd","@modelcontextprotocol/server-memory","stdio"]
startup_timeout_ms = 300000
timeout_ms = 600000

[projects.'\\?\C:\Users\hyper\fwber']
trust_level = "trusted"
