model = "gpt-5-codex"
model_reasoning_effort = "medium"
windows_wsl_setup_acknowledged = true

# Global MCP server timeout settings
mcp_server_startup_timeout_ms = 300000
mcp_server_timeout_ms = 600000

# WSL-compatible MCP servers (npx-based only)
[mcp_servers.memory]
command = "npx"
args = ["@modelcontextprotocol/server-memory","stdio"]
startup_timeout_ms = 300000
timeout_ms = 600000

[mcp_servers.everything]
command = "npx"
args = ["@modelcontextprotocol/server-everything","stdio"]
startup_timeout_ms = 300000
timeout_ms = 600000

[mcp_servers.filesystem]
command = "npx"
args = ["@modelcontextprotocol/server-filesystem","/mnt/c/Users/hyper/fwber"]
startup_timeout_ms = 300000
timeout_ms = 600000

[mcp_servers.sequential-thinking]
command = "npx"
args = ["@modelcontextprotocol/server-sequential-thinking","stdio"]
startup_timeout_ms = 300000
timeout_ms = 600000

[mcp_servers.gemini-mcp-tool]
command = "npx"
args = ["gemini-mcp-tool","stdio"]
startup_timeout_ms = 300000
timeout_ms = 600000

[projects.'/mnt/c/Users/hyper/fwber']
trust_level = "trusted"
