model = "gpt-5-codex-high"
model_reasoning_effort = "medium"
windows_wsl_setup_acknowledged = true

# Global MCP server timeout settings
mcp_server_startup_timeout_ms = 90000
mcp_server_timeout_ms = 30000

# Security: explicit env allowlist and filesystem roots (no wildcards)
[security]
env_allowlist = [
  "PROJECT_ROOT",
  "AI_COORDINATION_DIR",
  "MCP_CONFIG_PATH",
  "MCP_FILESYSTEM_ROOTS",
  "LOG_DIR",
  "TEMP_DIR",
  "SERENA_HOME",
  "ZEN_HOME",
  "OPENAI_API_KEY",
  "OPENAI_ORG",
  "ANTHROPIC_API_KEY",
  "GEMINI_API_KEY",
  "XAI_API_KEY",
  "OPENROUTER_API_KEY",
  "GITHUB_TOKEN",
  "POSTGRES_URL",
  "USERPROFILE",
  "PATH"
]
filesystem_roots = ["C:\\Users\\hyper\\fwber","C:\\Users\\hyper\\fwber\\AI_COORDINATION"]

# Stable MCP servers (Windows native)
[mcp_servers.sequential-thinking]
command = "cmd"
args = ["/c","npx.cmd","-y","@modelcontextprotocol/server-sequential-thinking","stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

[mcp_servers.memory]
command = "cmd"
args = ["/c","npx.cmd","-y","@modelcontextprotocol/server-memory","stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

[mcp_servers.filesystem]
command = "cmd"
args = ["/c","npx.cmd","-y","@modelcontextprotocol/server-filesystem","C:\\Users\\hyper\\fwber\\"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

[mcp_servers.gemini-mcp-tool]
command = "cmd"
args = ["/c","npx.cmd","-y","gemini-mcp-tool","stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

[mcp_servers.codex-mcp-server]
command = "cmd"
args = ["/c","npx.cmd","-y","codex-mcp-server","stdio"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Optional: Serena (requires uv installed at %USERPROFILE%\.local\bin\uv.exe)
[mcp_servers.serena]
command = "cmd"
args = ["/c","%USERPROFILE%\\.local\\bin\\uv.exe","run","--directory","%USERPROFILE%\\serena\\","serena","start-mcp-server","--context","codex","--project","C:\\Users\\hyper\\fwber\\"]
startup_timeout_ms = 90000
timeout_ms = 30000
enabled = true

# Project trust
[projects.'\\?\\C:\\Users\\hyper\\fwber']
trust_level = "trusted"