apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fwber.fullname" . }}-backend
  labels:
    {{- include "fwber.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "fwber.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "fwber.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php-fpm"]
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: APP_URL
              value: {{ .Values.env.APP_URL | quote }}
            - name: DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwber.fullname" . }}-backend
  labels:
    {{- include "fwber.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: fastcgi
      protocol: TCP
      name: fastcgi
  selector:
    {{- include "fwber.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
