apiVersion: v2
name: fwber
description: A Helm chart for deploying the fwber proxy dating platform (Laravel + Next.js + Rust)
type: application
version: 1.0.76
appVersion: "1.0.76"
dependencies:
  - name: mysql
    version: 9.10.x
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 18.0.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
