-- FWBer Database Setup Script
-- Run this script in MySQL to create the database

-- Create the database
CREATE DATABASE IF NOT EXISTS fwber CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Use the database
USE fwber;

-- Create the fwber_users table
CREATE TABLE IF NOT EXISTS fwber_users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    verify_hash VARCHAR(255) NULL,
    verified BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMP NULL,
    remember_token VARCHAR(100) NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    body_type VARCHAR(50) NULL,
    ethnicity VARCHAR(50) NULL,
    hair_color VARCHAR(50) NULL,
    hair_length VARCHAR(50) NULL,
    tattoos VARCHAR(50) NULL,
    overall_looks VARCHAR(50) NULL,
    intelligence VARCHAR(50) NULL,
    bedroom_personality VARCHAR(50) NULL,
    pubic_hair VARCHAR(50) NULL,
    penis_size VARCHAR(50) NULL,
    body_hair VARCHAR(50) NULL,
    breast_size VARCHAR(50) NULL,
    smoke_cigarettes BOOLEAN DEFAULT FALSE,
    light_drinker BOOLEAN DEFAULT FALSE,
    heavy_drinker BOOLEAN DEFAULT FALSE,
    smoke_marijuana BOOLEAN DEFAULT FALSE,
    psychedelics BOOLEAN DEFAULT FALSE,
    other_drugs BOOLEAN DEFAULT FALSE,
    have_warts BOOLEAN DEFAULT FALSE,
    have_herpes BOOLEAN DEFAULT FALSE,
    have_hepatitis BOOLEAN DEFAULT FALSE,
    have_other_sti BOOLEAN DEFAULT FALSE,
    have_hiv BOOLEAN DEFAULT FALSE,
    married_they_know BOOLEAN DEFAULT FALSE,
    married_secret BOOLEAN DEFAULT FALSE,
    poly BOOLEAN DEFAULT FALSE,
    disability BOOLEAN DEFAULT FALSE,
    postal_code VARCHAR(20) NULL,
    country VARCHAR(100) NULL,
    iso_country_code VARCHAR(2) NULL,
    city VARCHAR(100) NULL,
    state VARCHAR(100) NULL,
    lat DECIMAL(10,8) NULL,
    lon DECIMAL(11,8) NULL,
    public_text TEXT NULL,
    private_text TEXT NULL,
    avatar_url VARCHAR(255) NULL,
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_last_signed_in TIMESTAMP NULL,
    date_last_seen TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    INDEX idx_lat_lon (lat, lon),
    INDEX idx_gender (gender),
    INDEX idx_verified (verified),
    INDEX idx_date_last_seen (date_last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create the user_preferences table
CREATE TABLE IF NOT EXISTS user_preferences (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    want_age_from INT DEFAULT 18,
    want_age_to INT DEFAULT 99,
    want_gender_man BOOLEAN DEFAULT FALSE,
    want_gender_woman BOOLEAN DEFAULT FALSE,
    want_gender_ts_woman BOOLEAN DEFAULT FALSE,
    want_gender_ts_man BOOLEAN DEFAULT FALSE,
    want_gender_cd_woman BOOLEAN DEFAULT FALSE,
    want_gender_cd_man BOOLEAN DEFAULT FALSE,
    want_gender_couple_mf BOOLEAN DEFAULT FALSE,
    want_gender_couple_mm BOOLEAN DEFAULT FALSE,
    want_gender_couple_ff BOOLEAN DEFAULT FALSE,
    want_gender_group BOOLEAN DEFAULT FALSE,
    want_body_tiny BOOLEAN DEFAULT FALSE,
    want_body_slim BOOLEAN DEFAULT FALSE,
    want_body_average BOOLEAN DEFAULT FALSE,
    want_body_muscular BOOLEAN DEFAULT FALSE,
    want_body_curvy BOOLEAN DEFAULT FALSE,
    want_body_thick BOOLEAN DEFAULT FALSE,
    want_body_bbw BOOLEAN DEFAULT FALSE,
    want_ethnicity_white BOOLEAN DEFAULT FALSE,
    want_ethnicity_asian BOOLEAN DEFAULT FALSE,
    want_ethnicity_latino BOOLEAN DEFAULT FALSE,
    want_ethnicity_indian BOOLEAN DEFAULT FALSE,
    want_ethnicity_black BOOLEAN DEFAULT FALSE,
    want_ethnicity_other BOOLEAN DEFAULT FALSE,
    want_hair_color_light BOOLEAN DEFAULT FALSE,
    want_hair_color_medium BOOLEAN DEFAULT FALSE,
    want_hair_color_dark BOOLEAN DEFAULT FALSE,
    want_hair_color_red BOOLEAN DEFAULT FALSE,
    want_hair_color_gray BOOLEAN DEFAULT FALSE,
    want_hair_color_other BOOLEAN DEFAULT FALSE,
    want_hair_length_bald BOOLEAN DEFAULT FALSE,
    want_hair_length_short BOOLEAN DEFAULT FALSE,
    want_hair_length_medium BOOLEAN DEFAULT FALSE,
    want_hair_length_long BOOLEAN DEFAULT FALSE,
    want_tattoos_none BOOLEAN DEFAULT FALSE,
    want_tattoos_some BOOLEAN DEFAULT FALSE,
    want_tattoos_all_over BOOLEAN DEFAULT FALSE,
    want_looks_ugly BOOLEAN DEFAULT FALSE,
    want_looks_plain BOOLEAN DEFAULT FALSE,
    want_looks_quirks BOOLEAN DEFAULT FALSE,
    want_looks_average BOOLEAN DEFAULT FALSE,
    want_looks_attractive BOOLEAN DEFAULT FALSE,
    want_looks_hottie BOOLEAN DEFAULT FALSE,
    want_looks_supermodel BOOLEAN DEFAULT FALSE,
    want_intelligence_slow BOOLEAN DEFAULT FALSE,
    want_intelligence_bit_slow BOOLEAN DEFAULT FALSE,
    want_intelligence_average BOOLEAN DEFAULT FALSE,
    want_intelligence_faster BOOLEAN DEFAULT FALSE,
    want_intelligence_genius BOOLEAN DEFAULT FALSE,
    want_bedroom_personality_passive BOOLEAN DEFAULT FALSE,
    want_bedroom_personality_shy BOOLEAN DEFAULT FALSE,
    want_bedroom_personality_confident BOOLEAN DEFAULT FALSE,
    want_bedroom_personality_aggressive BOOLEAN DEFAULT FALSE,
    want_pubic_hair_shaved BOOLEAN DEFAULT FALSE,
    want_pubic_hair_trimmed BOOLEAN DEFAULT FALSE,
    want_pubic_hair_average BOOLEAN DEFAULT FALSE,
    want_pubic_hair_natural BOOLEAN DEFAULT FALSE,
    want_pubic_hair_hairy BOOLEAN DEFAULT FALSE,
    want_penis_size_tiny BOOLEAN DEFAULT FALSE,
    want_penis_size_skinny BOOLEAN DEFAULT FALSE,
    want_penis_size_average BOOLEAN DEFAULT FALSE,
    want_penis_size_thick BOOLEAN DEFAULT FALSE,
    want_penis_size_huge BOOLEAN DEFAULT FALSE,
    want_body_hair_smooth BOOLEAN DEFAULT FALSE,
    want_body_hair_average BOOLEAN DEFAULT FALSE,
    want_body_hair_hairy BOOLEAN DEFAULT FALSE,
    want_breast_size_tiny BOOLEAN DEFAULT FALSE,
    want_breast_size_small BOOLEAN DEFAULT FALSE,
    want_breast_size_average BOOLEAN DEFAULT FALSE,
    want_breast_size_large BOOLEAN DEFAULT FALSE,
    want_breast_size_huge BOOLEAN DEFAULT FALSE,
    want_safe_sex BOOLEAN DEFAULT FALSE,
    want_bareback_sex BOOLEAN DEFAULT FALSE,
    want_oral_give BOOLEAN DEFAULT FALSE,
    want_oral_receive BOOLEAN DEFAULT FALSE,
    want_anal_top BOOLEAN DEFAULT FALSE,
    want_anal_bottom BOOLEAN DEFAULT FALSE,
    want_filming BOOLEAN DEFAULT FALSE,
    want_voyeur BOOLEAN DEFAULT FALSE,
    want_exhibitionist BOOLEAN DEFAULT FALSE,
    want_roleplay BOOLEAN DEFAULT FALSE,
    want_spanking BOOLEAN DEFAULT FALSE,
    want_dom BOOLEAN DEFAULT FALSE,
    want_sub BOOLEAN DEFAULT FALSE,
    want_strapon BOOLEAN DEFAULT FALSE,
    want_cuckold BOOLEAN DEFAULT FALSE,
    want_furry BOOLEAN DEFAULT FALSE,
    where_my_place BOOLEAN DEFAULT FALSE,
    where_you_host BOOLEAN DEFAULT FALSE,
    where_car_date BOOLEAN DEFAULT FALSE,
    where_hotel_i_pay BOOLEAN DEFAULT FALSE,
    where_hotel_you_pay BOOLEAN DEFAULT FALSE,
    where_hotel_split BOOLEAN DEFAULT FALSE,
    where_bar_club BOOLEAN DEFAULT FALSE,
    where_gym_sauna BOOLEAN DEFAULT FALSE,
    where_nude_beach BOOLEAN DEFAULT FALSE,
    where_other BOOLEAN DEFAULT FALSE,
    mutual_long_term BOOLEAN DEFAULT FALSE,
    mutual_no_strings BOOLEAN DEFAULT FALSE,
    mutual_wear_mask BOOLEAN DEFAULT FALSE,
    mutual_only_play_safe BOOLEAN DEFAULT FALSE,
    mutual_proof_of_testing BOOLEAN DEFAULT FALSE,
    no_cigs BOOLEAN DEFAULT FALSE,
    no_light_drink BOOLEAN DEFAULT FALSE,
    no_heavy_drink BOOLEAN DEFAULT FALSE,
    no_marijuana BOOLEAN DEFAULT FALSE,
    no_psychedelics BOOLEAN DEFAULT FALSE,
    no_drugs BOOLEAN DEFAULT FALSE,
    no_herpes BOOLEAN DEFAULT FALSE,
    no_warts BOOLEAN DEFAULT FALSE,
    no_hepatitis BOOLEAN DEFAULT FALSE,
    no_other_stis BOOLEAN DEFAULT FALSE,
    no_hiv BOOLEAN DEFAULT FALSE,
    no_married_they_know BOOLEAN DEFAULT FALSE,
    no_married_secret BOOLEAN DEFAULT FALSE,
    no_poly BOOLEAN DEFAULT FALSE,
    no_disabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES fwber_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create the matches table
CREATE TABLE IF NOT EXISTS matches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user1_id BIGINT UNSIGNED NOT NULL,
    user2_id BIGINT UNSIGNED NOT NULL,
    status ENUM('pending', 'accepted', 'rejected', 'blocked') DEFAULT 'pending',
    match_score INT DEFAULT 0,
    matched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY unique_match (user1_id, user2_id),
    INDEX idx_user1_status (user1_id, status),
    INDEX idx_user2_status (user2_id, status),
    INDEX idx_match_score (match_score),
    FOREIGN KEY (user1_id) REFERENCES fwber_users(id) ON DELETE CASCADE,
    FOREIGN KEY (user2_id) REFERENCES fwber_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create geographic tables
CREATE TABLE IF NOT EXISTS zipgeo (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    zip5 VARCHAR(5) NOT NULL,
    city VARCHAR(250) NOT NULL,
    state VARCHAR(250) NOT NULL,
    lat DECIMAL(10,8) NOT NULL,
    lon DECIMAL(11,8) NOT NULL,
    county VARCHAR(250) NOT NULL,
    INDEX idx_zip5 (zip5),
    INDEX idx_lat_lon (lat, lon)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zipgeoworld (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    iso_country_code VARCHAR(2) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    city VARCHAR(180) NOT NULL,
    state VARCHAR(100) NOT NULL,
    state_code VARCHAR(20) NOT NULL,
    county1 VARCHAR(100) NOT NULL,
    county2 VARCHAR(20) NOT NULL,
    community1 VARCHAR(100) NOT NULL,
    community2 VARCHAR(20) NOT NULL,
    lat DECIMAL(10,8) NOT NULL,
    lon DECIMAL(11,8) NOT NULL,
    accuracy INT NOT NULL,
    INDEX idx_country_postal (iso_country_code, postal_code),
    INDEX idx_lat_lon (lat, lon)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS countrycodes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    iso_country_code VARCHAR(2) UNIQUE NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    country_name_short VARCHAR(50) NOT NULL,
    INDEX idx_iso_country_code (iso_country_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert some basic country codes
INSERT INTO countrycodes (iso_country_code, country_name, country_name_short) VALUES
('US', 'United States', 'USA'),
('CA', 'Canada', 'Canada'),
('GB', 'United Kingdom', 'UK'),
('AU', 'Australia', 'Australia'),
('DE', 'Germany', 'Germany'),
('FR', 'France', 'France'),
('IT', 'Italy', 'Italy'),
('ES', 'Spain', 'Spain'),
('NL', 'Netherlands', 'Netherlands'),
('BE', 'Belgium', 'Belgium'),
('CH', 'Switzerland', 'Switzerland'),
('AT', 'Austria', 'Austria'),
('SE', 'Sweden', 'Sweden'),
('NO', 'Norway', 'Norway'),
('DK', 'Denmark', 'Denmark'),
('FI', 'Finland', 'Finland'),
('PL', 'Poland', 'Poland'),
('CZ', 'Czech Republic', 'Czech Republic'),
('HU', 'Hungary', 'Hungary'),
('RO', 'Romania', 'Romania'),
('BG', 'Bulgaria', 'Bulgaria'),
('HR', 'Croatia', 'Croatia'),
('SI', 'Slovenia', 'Slovenia'),
('SK', 'Slovakia', 'Slovakia'),
('LT', 'Lithuania', 'Lithuania'),
('LV', 'Latvia', 'Latvia'),
('EE', 'Estonia', 'Estonia'),
('IE', 'Ireland', 'Ireland'),
('PT', 'Portugal', 'Portugal'),
('GR', 'Greece', 'Greece'),
('CY', 'Cyprus', 'Cyprus'),
('MT', 'Malta', 'Malta'),
('LU', 'Luxembourg', 'Luxembourg'),
('IS', 'Iceland', 'Iceland'),
('LI', 'Liechtenstein', 'Liechtenstein'),
('MC', 'Monaco', 'Monaco'),
('SM', 'San Marino', 'San Marino'),
('VA', 'Vatican City', 'Vatican'),
('AD', 'Andorra', 'Andorra'),
('MX', 'Mexico', 'Mexico'),
('BR', 'Brazil', 'Brazil'),
('AR', 'Argentina', 'Argentina'),
('CL', 'Chile', 'Chile'),
('CO', 'Colombia', 'Colombia'),
('PE', 'Peru', 'Peru'),
('VE', 'Venezuela', 'Venezuela'),
('EC', 'Ecuador', 'Ecuador'),
('BO', 'Bolivia', 'Bolivia'),
('PY', 'Paraguay', 'Paraguay'),
('UY', 'Uruguay', 'Uruguay'),
('GY', 'Guyana', 'Guyana'),
('SR', 'Suriname', 'Suriname'),
('FK', 'Falkland Islands', 'Falkland Islands'),
('GF', 'French Guiana', 'French Guiana'),
('JP', 'Japan', 'Japan'),
('CN', 'China', 'China'),
('KR', 'South Korea', 'South Korea'),
('IN', 'India', 'India'),
('TH', 'Thailand', 'Thailand'),
('VN', 'Vietnam', 'Vietnam'),
('MY', 'Malaysia', 'Malaysia'),
('SG', 'Singapore', 'Singapore'),
('ID', 'Indonesia', 'Indonesia'),
('PH', 'Philippines', 'Philippines'),
('TW', 'Taiwan', 'Taiwan'),
('HK', 'Hong Kong', 'Hong Kong'),
('MO', 'Macau', 'Macau'),
('MN', 'Mongolia', 'Mongolia'),
('KZ', 'Kazakhstan', 'Kazakhstan'),
('UZ', 'Uzbekistan', 'Uzbekistan'),
('KG', 'Kyrgyzstan', 'Kyrgyzstan'),
('TJ', 'Tajikistan', 'Tajikistan'),
('TM', 'Turkmenistan', 'Turkmenistan'),
('AF', 'Afghanistan', 'Afghanistan'),
('PK', 'Pakistan', 'Pakistan'),
('BD', 'Bangladesh', 'Bangladesh'),
('LK', 'Sri Lanka', 'Sri Lanka'),
('NP', 'Nepal', 'Nepal'),
('BT', 'Bhutan', 'Bhutan'),
('MV', 'Maldives', 'Maldives'),
('MM', 'Myanmar', 'Myanmar'),
('LA', 'Laos', 'Laos'),
('KH', 'Cambodia', 'Cambodia'),
('BN', 'Brunei', 'Brunei'),
('TL', 'Timor-Leste', 'Timor-Leste'),
('PG', 'Papua New Guinea', 'Papua New Guinea'),
('FJ', 'Fiji', 'Fiji'),
('NC', 'New Caledonia', 'New Caledonia'),
('VU', 'Vanuatu', 'Vanuatu'),
('SB', 'Solomon Islands', 'Solomon Islands'),
('TO', 'Tonga', 'Tonga'),
('WS', 'Samoa', 'Samoa'),
('KI', 'Kiribati', 'Kiribati'),
('TV', 'Tuvalu', 'Tuvalu'),
('NR', 'Nauru', 'Nauru'),
('PW', 'Palau', 'Palau'),
('MH', 'Marshall Islands', 'Marshall Islands'),
('FM', 'Micronesia', 'Micronesia'),
('CK', 'Cook Islands', 'Cook Islands'),
('NU', 'Niue', 'Niue'),
('TK', 'Tokelau', 'Tokelau'),
('AS', 'American Samoa', 'American Samoa'),
('GU', 'Guam', 'Guam'),
('MP', 'Northern Mariana Islands', 'Northern Mariana Islands'),
('PF', 'French Polynesia', 'French Polynesia'),
('WF', 'Wallis and Futuna', 'Wallis and Futuna'),
('TK', 'Tokelau', 'Tokelau'),
('NU', 'Niue', 'Niue'),
('CK', 'Cook Islands', 'Cook Islands'),
('FM', 'Micronesia', 'Micronesia'),
('MH', 'Marshall Islands', 'Marshall Islands'),
('PW', 'Palau', 'Palau'),
('NR', 'Nauru', 'Nauru'),
('TV', 'Tuvalu', 'Tuvalu'),
('KI', 'Kiribati', 'Kiribati'),
('WS', 'Samoa', 'Samoa'),
('TO', 'Tonga', 'Tonga'),
('SB', 'Solomon Islands', 'Solomon Islands'),
('VU', 'Vanuatu', 'Vanuatu'),
('NC', 'New Caledonia', 'New Caledonia'),
('FJ', 'Fiji', 'Fiji'),
('PG', 'Papua New Guinea', 'Papua New Guinea'),
('TL', 'Timor-Leste', 'Timor-Leste'),
('BN', 'Brunei', 'Brunei'),
('KH', 'Cambodia', 'Cambodia'),
('LA', 'Laos', 'Laos'),
('MM', 'Myanmar', 'Myanmar'),
('MV', 'Maldives', 'Maldives'),
('BT', 'Bhutan', 'Bhutan'),
('NP', 'Nepal', 'Nepal'),
('LK', 'Sri Lanka', 'Sri Lanka'),
('BD', 'Bangladesh', 'Bangladesh'),
('PK', 'Pakistan', 'Pakistan'),
('AF', 'Afghanistan', 'Afghanistan'),
('TM', 'Turkmenistan', 'Turkmenistan'),
('TJ', 'Tajikistan', 'Tajikistan'),
('KG', 'Kyrgyzstan', 'Kyrgyzstan'),
('UZ', 'Uzbekistan', 'Uzbekistan'),
('KZ', 'Kazakhstan', 'Kazakhstan'),
('MN', 'Mongolia', 'Mongolia'),
('MO', 'Macau', 'Macau'),
('HK', 'Hong Kong', 'Hong Kong'),
('TW', 'Taiwan', 'Taiwan'),
('PH', 'Philippines', 'Philippines'),
('ID', 'Indonesia', 'Indonesia'),
('SG', 'Singapore', 'Singapore'),
('MY', 'Malaysia', 'Malaysia'),
('VN', 'Vietnam', 'Vietnam'),
('TH', 'Thailand', 'Thailand'),
('IN', 'India', 'India'),
('KR', 'South Korea', 'South Korea'),
('CN', 'China', 'China'),
('JP', 'Japan', 'Japan'),
('GF', 'French Guiana', 'French Guiana'),
('FK', 'Falkland Islands', 'Falkland Islands'),
('SR', 'Suriname', 'Suriname'),
('GY', 'Guyana', 'Guyana'),
('UY', 'Uruguay', 'Uruguay'),
('PY', 'Paraguay', 'Paraguay'),
('BO', 'Bolivia', 'Bolivia'),
('EC', 'Ecuador', 'Ecuador'),
('VE', 'Venezuela', 'Venezuela'),
('PE', 'Peru', 'Peru'),
('CO', 'Colombia', 'Colombia'),
('CL', 'Chile', 'Chile'),
('AR', 'Argentina', 'Argentina'),
('BR', 'Brazil', 'Brazil'),
('MX', 'Mexico', 'Mexico'),
('AD', 'Andorra', 'Andorra'),
('VA', 'Vatican City', 'Vatican'),
('SM', 'San Marino', 'San Marino'),
('MC', 'Monaco', 'Monaco'),
('LI', 'Liechtenstein', 'Liechtenstein'),
('IS', 'Iceland', 'Iceland'),
('LU', 'Luxembourg', 'Luxembourg'),
('MT', 'Malta', 'Malta'),
('CY', 'Cyprus', 'Cyprus'),
('GR', 'Greece', 'Greece'),
('PT', 'Portugal', 'Portugal'),
('IE', 'Ireland', 'Ireland'),
('EE', 'Estonia', 'Estonia'),
('LV', 'Latvia', 'Latvia'),
('LT', 'Lithuania', 'Lithuania'),
('SK', 'Slovakia', 'Slovakia'),
('SI', 'Slovenia', 'Slovenia'),
('HR', 'Croatia', 'Croatia'),
('BG', 'Bulgaria', 'Bulgaria'),
('RO', 'Romania', 'Romania'),
('HU', 'Hungary', 'Hungary'),
('CZ', 'Czech Republic', 'Czech Republic'),
('PL', 'Poland', 'Poland'),
('FI', 'Finland', 'Finland'),
('DK', 'Denmark', 'Denmark'),
('NO', 'Norway', 'Norway'),
('SE', 'Sweden', 'Sweden'),
('AT', 'Austria', 'Austria'),
('CH', 'Switzerland', 'Switzerland'),
('BE', 'Belgium', 'Belgium'),
('NL', 'Netherlands', 'Netherlands'),
('ES', 'Spain', 'Spain'),
('IT', 'Italy', 'Italy'),
('FR', 'France', 'France'),
('DE', 'Germany', 'Germany'),
('AU', 'Australia', 'Australia'),
('GB', 'United Kingdom', 'UK'),
('CA', 'Canada', 'Canada');

-- Show success message
SELECT 'FWBer database setup completed successfully!' as message;
