replicaCount: 1

image:
  repository: my-docker-registry/fwber
  pullPolicy: IfNotPresent
  tag: ""

backend:
  replicaCount: 2
  image:
    repository: my-docker-registry/fwber-backend
    tag: "latest"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

frontend:
  replicaCount: 2
  image:
    repository: my-docker-registry/fwber-frontend
    tag: "latest"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

worker:
  replicaCount: 2

reverb:
  replicaCount: 2
  service:
    port: 8080

geo:
  replicaCount: 1
  image:
    repository: my-docker-registry/fwber-geo
    tag: "latest"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.fwber.me
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: fwber-backend
            port: 80
    - host: ws.fwber.me
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: fwber-reverb
            port: 8080
    - host: fwber.me
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: fwber-frontend
            port: 3000

env:
  APP_ENV: production
  APP_URL: "https://api.fwber.me"
  FRONTEND_URL: "https://fwber.me"

mysql:
  enabled: true
  auth:
    database: fwber
    username: fwber_user
    password: secretpassword
    rootPassword: supersecretpassword

redis:
  enabled: true
  auth:
    password: secretredispassword
