import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://fwber.me'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/roast',
          '/roast-date',
          '/rate-my-pussy',
          '/discover',
          '/nearby',
          '/recommendations',
          '/events',
          '/venues',
          '/groups',
          '/topics',
          '/marketplace',
          '/premium',
          '/leaderboard',
          '/achievements',
          '/local-pulse',
          '/date-ideas',
          '/date-planner',
          '/deals',
          '/places',
          '/referrals',
          '/login',
          '/register',
          '/forgot-password',
          '/help',
          '/support',
          '/contact',
          '/safety',
          '/privacy',
          '/terms',
          '/feedback',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/messages/',
          '/settings/',
          '/matches/',
          '/notifications/',
          '/activity/',
          '/friends/',
          '/photos/',
          '/profile-views/',
          '/search/',
          '/boosts/',
          '/gifts/',
          '/wallet/',
          '/subscription/',
          '/unlocks/',
          '/journal/',
          '/journals/',
          '/scrapbook/',
          '/daily-checkin/',
          '/ice-breakers/',
          '/content-generation/',
          '/identity/',
          '/reputation/',
          '/wingman/',
          '/studio/',
          '/chatrooms/',
          '/proximity-chatrooms/',
          '/bulletin-boards/',
          '/burner-links/',
          '/spaces/',
          '/commerce/',
          '/merchant/',
          '/economy/',
          '/analytics/',
          '/operations/',
          '/moderation/',
          '/federation/',
          '/integrations/',
          '/proximity/',
          '/scenes/',
          '/plans/',
          '/conference-pulse/',
          '/council/',
          '/reports/',
          '/onboarding/',
          '/location-settings/',
          '/test-auth',
          '/dev-auth',
          '/sentry-test',
          '/api-test',
          '/tier-demo',
          '/verify',
          '/verify-email',
          '/_next/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
