version: '3.8'

services:
  mercure:
    image: dunglas/mercure:latest
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY}"
      MERCURE_CORS_ALLOWED_ORIGINS: "${APP_URL}"
      MERCURE_PUBLISH_ALLOWED_ORIGINS: "${API_URL}"
      MERCURE_SUBSCRIPTIONS: "1"
      MERCURE_EXTRA_DIRECTIVES: |
        subscriptions
        heartbeat 10s
        write_timeout 30s
        read_timeout 30s
    ports:
      - "3001:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/.well-known/mercure"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
